project:
  type: book

book:
  title: "Spectral Analysis for Paleo Data"
  author: "Thomas Laepple, Andrew Dolman"
  date: "2/26/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - quick-start.qmd
    - part: Estimating powerspectra
      chapters:
        - regular-timeseries.qmd
        - irregular-timeseries.qmd
    - part: Variance
      chapters:
        - variance.qmd
    - part: Simulating Timeseries
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: source

